FROM python:3.8

RUN mkdir -p /opt/services/sofia_web_app/src
WORKDIR /opt/services/sofia_web_app/src

RUN pip install gunicorn django

COPY . /opt/services/sofia_web_app/src
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN python sofiax_web/manage.py collectstatic --no-input

EXPOSE 8000

CMD ["gunicorn", "--chdir", "sofiax_web", "--bind", ":8000", "sofiax_web.wsgi:application"]
