version: '3.5'

services:

  sofiax_web_app:
    image: sofiax_web_app
    container_name: sofiax_web_app
    build:
      context: .
      dockerfile: Dockerfile.gun
    volumes:
      - .:/opt/services/sofia_web_app/src
      - static_volume:/opt/services/sofia_web_app/static  # <-- bind the static volume
      - media_volume:/opt/services/sofia_web_app/media  # <-- bind the media volume
    networks:
      - sofiax_network

  sofiax_nginx:
    image: sofiax_nginx
    container_name: sofiax_ngnix
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/ssl.conf:/config/nginx/ssl.conf
      - static_volume:/opt/services/sofia_web_app/static  # <-- bind the static volume
      - media_volume:/opt/services/sofia_web_app/media  # <-- bind the media volume
    depends_on:  # <-- wait for sofia_web_app to be "ready" before starting this service
      - sofiax_web_app
    networks:
      - sofiax_network

  sofiax_vo:
    image: sofiax_vo
    container_name: sofiax_vo
    build:
      context: .
      dockerfile: Dockerfile.vo
    env_file:
      - ./config/vo/vo.env
    ports:
      - 8080:8080
    networks:
      - sofiax_network

networks:
  sofiax_network:
    name: sofiax_network
    driver: bridge

volumes:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume