version: '3'

services:

  sofia_web_app:
    build:
      context: .
      dockerfile: Dockerfile.gun
    volumes:
      - .:/opt/services/sofia_web_app/src
      - static_volume:/opt/services/sofia_web_app/static  # <-- bind the static volume
      - media_volume:/opt/services/sofia_web_app/media  # <-- bind the media volume
    networks:
      - nginx_network

  nginx:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Perth/Australia
      - URL=wallaby.aussrc.org
      - SUBDOMAINS=
      - VALIDATION=http
      - EMAIL=dave.pallot@icrar.org

    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

    volumes:
      - ./config/nginx/default.conf:/config/nginx/site-confs/default
      - .:/opt/services/sofia_web_app/src
      - static_volume:/opt/services/sofia_web_app/static  # <-- bind the static volume
      - media_volume:/opt/services/sofia_web_app/media  # <-- bind the media volume
    networks:
      - nginx_network


networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume