DETECTION_SCHEMA = {
    "name": None,
    "x": None,
    "y": None,
    "z": None,
    "x_min": None,
    "x_max": None,
    "y_min": None,
    "z_min": None,
    "z_max": None,
    "n_pix": None,
    "f_min": None,
    "f_max": None,
    "f_sum": None,
    "rel": None,
    "rms": None,
    "w20": None,
    "w50": None,
    "ell_maj": None,
    "ell_min": None,
    "ell_pa": None,
    "ell3s_maj": None,
    "ell3s_pa": None,
    "kin_pa": None,
    "ra": None,
    "dec": None,
    "l": None,
    "b": None,
    "v_rad": None,
    "v_opt": None,
    "v_app": None,
    "err_x": None,
    "err_y": None,
    "err_z": None,
    "err_f_sum": None,
    "freq": None,
    "flag": None
}

VO_DATALINK_URL = 'https://wallaby.aussrc.org/wallaby/vo/dl/dlmeta?ID='
