##
## Copyright (c) 2021 AusSRC.
##
## This file is part of SoFiAX
## (see https://github.com/AusSRC/SoFiAX).
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU Lesser General Public License as published by
## the Free Software Foundation, either version 2.1 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public License
## along with this program. If not, see <http://www.gnu.org/licenses/>.##

# Functional tests for SoFiAX
# Ensures that execution will run successfully and write the correct information
# to the database.

name: Functional tests
on: [push]
jobs:
  # Run SoFiAX just to write an existing output from SoFiA
  # to the database. Ensure that the output is consistent.
  database_write:  
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'
          architecture: 'x64'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - run: pip3 install -r requirements.txt
      - run: python3 setup.py install
      - run: sofiax -c /home/ubuntu/data/database_write/config.ini -p /home/ubuntu/data/database_write/sofia.par

      # store database query in file
      - name: Check database content
        env:
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
        run: |
          sh /home/ubuntu/scripts/test_case_output.sh

      # compare database content and cleanup
      - run: cmp $HOME/scripts/test_case_detection_count $HOME/data/database_write/reference_detection_count || exit 1
      - run: cmp $HOME/scripts/test_case_detection_output $HOME/data/database_write/reference_detection_output  || exit 1
      - run: sh $HOME/scripts/cleanup.sh

  # Run SoFiAX as a wrapper for SoFiA
  # Ensure there are no errors.
  wrapper_single:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'
          architecture: 'x64'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - run: pip3 install -r requirements.txt
      - run: python3 setup.py install
      - run: sofiax -c /home/ubuntu/data/wrapper_single/config.ini -p /home/ubuntu/data/wrapper_single/sofia.par

  # Encountered an error in SoFiAX relating to transactions
  transaction:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'
          architecture: 'x64'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - run: pip3 install -r requirements.txt
      - run: python3 setup.py install
      - run: sofiax -c /home/ubuntu/data/transaction/config.ini -p /home/ubuntu/data/transaction/sofia_058.par
