name: Functional tests
on: [push]
jobs:
  # setup:
    # runs-on: self-hosted
    # steps:
    #   - uses: actions/checkout@v2
    #   - uses: actions/setup-python@v2
    #     with:
    #       python-version: '3.8.0'
    #       architecture: 'x64'
    #   - name: Cache pip
    #     uses: actions/cache@v2
    #     with:
    #       path: ~/.cache/pip
    #       key: ${{ runner.os }}-build-${{ env.cache-name }}
    #       restore-keys: |
    #         ${{ runner.os }}-build-${{ env.cache-name }}
    #   - run: pip3 install -r requirements.txt
    #   - run: python3 setup.py install

  test_case:
    runs-on: self-hosted
    steps:
      # install and run sofiax 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'
          architecture: 'x64'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - run: pip3 install -r requirements.txt
      - run: python3 setup.py install
      - run: cp -r /home/ubuntu/data/test_case test_case
      - run: sofiax -c test_case/config.ini -p test_case/sofia.par

      # store database query in file
      - name: Check database content
        env:
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
        run: |
          sh /home/ubuntu/scripts/test_case_output.sh

      # compare database content and cleanup
      - run: cmp $HOME/scripts/test_case_detection_count $HOME/data/test_case/reference_detection_count || exit 1
      - run: cmp $HOME/scripts/test_case_detection_output $HOME/data/test_case/reference_detection_output  || exit 1
      - run: sh /home/ubuntu/scripts/cleanup.sh